services:
  postgres:
    image: postgres:15-alpine
    container_name: ape_chat_db
    environment:
      POSTGRES_USER: apeuser
      POSTGRES_PASSWORD: apepass
      POSTGRES_DB: apechat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apeuser -d apechat"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: ape_chat_postgres_data